In [1]:
# install the following modules if never used them before
# ! pip install opencv-python
# ! pip install scipy
# ! pip install imutils
# ! pip install opencv-contrib-python

In [1]:
# import modules

from scipy.spatial import distance as dist

import cv2
import numpy as np
import argparse
import imutils
from matplotlib import pyplot as plt

# Test parameters

* change only the treshold of the first black and white threshold ?

In [33]:
extension = 'Adipocytes/ID17-383d-15082019-ES.tif'


# import original
original = cv2.imread(extension)

# get grayscale version and re-size it
gray = cv2.cvtColor(original, cv2.COLOR_BGR2GRAY)

# apply a black-and-white threshold
# determine the treshold: mean of the image
thresh_bw = gray.mean()
(thresh, bw) = cv2.threshold(gray, thresh_bw, 255, cv2.THRESH_BINARY)
# alpha between 200 and 250 usually
# I tried putting a contrast first and it doesn't make it better

# blurr the image
blurred = cv2.GaussianBlur(bw, (27,27), 0)
# erode and dilate
kernel = np.ones((5,5),np.uint8)
eroded = cv2.erode(blurred,kernel,iterations = 7)
dilated = cv2.dilate(eroded,kernel,iterations = 7)

# apply a second black-and-white threshold

(thresh, bw_2) = cv2.threshold(dilated, 200, 255, cv2.THRESH_BINARY)

# find the edges
edged = cv2.Canny(bw_2, 150, 300)

# find and measure contours
contours = cv2.findContours(edged.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contours = imutils.grab_contours(contours)

cv2.drawContours(original, contours, -1, (0, 255, 0), 2)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 240, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 226, 245],
        [255, 255, 255]],

       [[255, 231, 255],
        [255, 255, 255],
        [255, 246, 255],
        ...,
        [255, 255, 255],
        [255, 221, 237],
        [255, 255, 255]],

       ...,

       [[208, 253, 238],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [217, 238, 231],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255,   0, 255]]

In [36]:
cv2.imshow("first black and white threshold", bw)
cv2.imshow("second black and white threshold", bw_2)
cv2.waitKey(0)

-1

In [35]:
cv2.imshow("done", original)
cv2.waitKey(0)

-1

In [32]:
print(dilated.mean())

181.00253092447917


# Measure cell area

In [77]:
cnt = contours[0]
area = cv2.contourArea(cnt)
print(area)
perimeter = cv2.arcLength(cnt,True)
print(perimeter)

epsilon = 0.1*cv2.arcLength(cnt,True)
approx = cv2.approxPolyDP(cnt,epsilon,True)
print(approx)

11.5
448.89444279670715
[[[1132  884]]

 [[1149  959]]

 [[1131  883]]

 [[1054  959]]]


In [ ]:
pixelsPerMetric = 0.1
# loop over the contours individually
for c in cnts:
	# if the contour is not sufficiently large, ignore it
	if cv2.contourArea(c) < 100:
		continue
	# compute the rotated bounding box of the contour
	orig = image.copy()
	box = cv2.minAreaRect(c)
	box = cv2.cv.BoxPoints(box) if imutils.is_cv2() else cv2.boxPoints(box)
	box = np.array(box, dtype="int")
	# order the points in the contour such that they appear
	# in top-left, top-right, bottom-right, and bottom-left
	# order, then draw the outline of the rotated bounding
	# box
	box = perspective.order_points(box)
	cv2.drawContours(orig, [box.astype("int")], -1, (0, 255, 0), 2)
	# loop over the original points and draw them
	for (x, y) in box:
		cv2.circle(orig, (int(x), int(y)), 5, (0, 0, 255), -1)